---
groups:
  - name: concourse-oci-object
    jobs:
      - publish-resource
      - fetch-objects

jobs:
  - name: publish-resource
    serial: true
    plan:
      - aggregate:
        - {trigger: true, get: package-src}
      - task: build-package
        config:
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 2-alpine
          platform: linux
          inputs:
          - name: package-src
          outputs:
          - name: package-out
          run:
            path: sh
            args:
            - -exc
            - |
              cd package-src
              python setup.py sdist
              mkdir ../package-out/dist
              cp Dockerfile ../package-out
              cp dist/*.tar.gz ../package-out/dist
      - put: package-image
        params:
          build: package-out

  - name: fetch-objects
    serial: true
    plan:
      - aggregate:
        - {trigger: true, passed: [publish-resource], get: package-image}
        - {trigger: true, get: small-file, resource: small-file}
        - {trigger: true, get: large-file, resource: large-file}
      - task: list-downloads
        config:
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 2-alpine
          platform: linux
          inputs:
          - name: small-file
          - name: large-file
          run:
            path: sh
            args:
            - -exc
            - |
              ls -al small-file
              ls -al large-file

resources:
  - name: package-src
    type: git
    source:
      uri: https://github.com/((github-org))/ocios-resource.git
      username: ((github-user))
      password: ((github-password))

  - name: package-image
    type: docker-image
    source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: {{docker-hub-repo}}

  - name: small-file
    type: ocios-resource
    source:
      ns:          {{oracle-namespace}}
      bucket:      {{oracle-bucket}}
      user:        {{oracle-user}}
      fingerprint: {{oracle-fingerprint}}
      apikey:      {{oracle-apikey}}
      tenancy:     {{oracle-tenancy}}
      region:      {{oracle-region}}
      regexp:      test-([0-9]+)\.txt

  - name: large-file
    type: ocios-resource
    source:
      ns:          {{oracle-namespace}}
      bucket:      "cpi-dev-releases"
      user:        {{oracle-user}}
      fingerprint: {{oracle-fingerprint}}
      apikey:      {{oracle-apikey}}
      tenancy:     {{oracle-tenancy}}
      region:      {{oracle-region}}
      regexp:      bosh-oracle-cpi-dev-([0-9]+\.[0-9]+\.[0-9]+)\.tgz

resource_types:
  - name: ocios-resource
    type: docker-image
    source:
      repository: {{docker-hub-repo}}
